=== fdepablo/WsXMLUEM/02_DTD/pelicula.dtd
<!ELEMENT pelicula (titulo,fecha,actores,director)>
<!ATTLIST pelicula id CDATA #REQUIRED>
<!ATTLIST pelicula categoria CDATA #REQUIRED>

<!ELEMENT titulo (#PCDATA)>
<!ELEMENT fecha (#PCDATA)>
<!ELEMENT actores (actor+)>

<!ELEMENT actor (nombre,edad)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT edad (#PCDATA)>

<!ELEMENT director (#PCDATA)>

=== fdepablo/WsXMLUEM/02_DTD/peliculaTDTExterno.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE pelicula SYSTEM "pelicula.dtd">
<pelicula id="1" categoria="sci-fi">
    <titulo>La guerra de las galaxias</titulo>
    <fecha>22/07/1977</fecha>
    <actores>
        <actor>
            <nombre>Luke</nombre>
            <edad>29</edad>
        </actor>
        <actor>
            <nombre>Han solo</nombre>
            <edad>39</edad>
        </actor>
    </actores>
    <director>pepe</director>
</pelicula>
