=== fdepablo/WsXMLUEM/03_Schemas/ejercicio3Persona/personas.xsd
<schema xmlns="http://www.w3.org/2001/XMLSchema">
    <element name="personas">
        <complexType>
            <sequence>
                <element name="persona" minOccurs="1" maxOccurs="unbounded">
                    <complexType>
                        <sequence>
                            <element name="nombre" type="string"/>
                            <element name="apellidos" type="string" minOccurs="1" maxOccurs="unbounded"/>
                            <element name="edad" type="integer"></element>
                        </sequence>                        
                    </complexType>
                </element>
            </sequence>
        </complexType>
    </element>
</schema>

=== fdepablo/WsXMLUEM/03_Schemas/ejercicio3Persona/personas.xml
<?xml version="1.0" encoding="UTF-8"?>
<personas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation= "personas.xsd">
    <persona>
        <nombre>Homer</nombre>
        <apellidos>Simpson</apellidos>
        <apellidos>J</apellidos>
        <edad>40</edad>
    </persona>
    <persona>
        <nombre>Marge</nombre>
        <apellidos>Simpson</apellidos>
        <apellidos>R</apellidos>
        <edad>34</edad>
    </persona>
</personas>
